--liquibase formatted sql

--changeset ibodnar:base-table-structure splitStatements:FALSE
CREATE TABLE authors
(
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL,
  email TEXT NOT NULL
);

CREATE TABLE genres
(
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE books
(
  isbn             TEXT          NOT NULL PRIMARY KEY,
  title            TEXT          NOT NULL,
  publisher        TEXT          NOT NULL,
  publication_date DATE          NOT NULL,
  genre_id         BIGINT        NOT NULL references genres (id),
  description      TEXT          NOT NULL,
  language         TEXT          NOT NULL,
  pages            INT           NOT NULL,
  price            NUMERIC(7, 2) NOT NULL
);

CREATE table books_to_authors
(
  book_isbn TEXT   NOT NULL REFERENCES books (isbn),
  author_id BIGINT NOT NULL REFERENCES authors (id)
);
