version: '3.3'
services:
  eurekaserver:
    image: eurekaserver:alpine
    ports:
      - "8761:8761"
#    networks:
#      backend:
#        aliases:
#          - "configserver"
#networks:
#  backend:
#    external: true
#    driver: bridge