version: '3.3'
services:
  eurekaserver:
    image: eurekaserver:alpine
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
networks:
  backend:
    driver: bridge