version: '3.3'
services:
  book-database:
    image: postgres:16.8-alpine3.21
    ports:
      - "5832:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "book"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ~/PostgreSQL/16/book/data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "book-database-master"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  author-database:
    image: postgres:16.8-alpine3.21
    ports:
      - "5833:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "author"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ~/PostgreSQL/16/author/data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "author-database-master"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  genre-database:
    image: postgres:16.8-alpine3.21
    ports:
      - "5834:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "genre"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ~/PostgreSQL/16/genre/data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "genre-database-master"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  publisher-database:
    image: postgres:16.8-alpine3.21
    ports:
      - "5835:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "publisher"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ~/PostgreSQL/16/publisher/data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "publisher-database-master"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  config-service:
    image: config-service:alpine
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  eureka-service:
    image: eureka-service:alpine
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    networks:
      backend:
        aliases:
          - "eureka-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  gateway-service:
    image: gateway-service:alpine
    ports:
      - "8090:8090"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
        - config-service
        - eureka-service
    networks:
      backend:
        aliases:
          - "gateway-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  author-service:
    image: author-service:alpine
    ports:
      - "8092:8092"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - config-service
      - eureka-service
      - author-database
    networks:
      backend:
        aliases:
          - "author-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  book-service:
    image: book-service:alpine
    ports:
      - "8095:8095"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - config-service
      - eureka-service
      - book-database
    networks:
      backend:
        aliases:
          - "book-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  genre-service:
      image: genre-service:alpine
      ports:
        - "8093:8093"
      environment:
        - "SPRING_PROFILES_ACTIVE=prod"
      depends_on:
        - config-service
        - eureka-service
        - genre-database
      networks:
        backend:
          aliases:
            - "genre-service"
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 5
          window: 60s
  publisher-service:
    image: publisher-service:alpine
    ports:
      - "8094:8094"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - config-service
      - eureka-service
      - publisher-database
    networks:
      backend:
        aliases:
          - "publisher-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  bookstore-service:
    image: bookstore-service:alpine
    ports:
      - "8091:8091"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - config-service
      - eureka-service
    networks:
      backend:
        aliases:
          - "bookstore-service"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  bookstore-web-application:
    image: bookstore-web-application:alpine
    ports:
      - "4200:4200"
    networks:
      backend:
        aliases:
          - "bookstore-web-application"
networks:
  backend:
    external: true