<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.bookstore</groupId>
  <artifactId>microservices</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>bookstore-service</module>
    <module>eureka-server</module>
    <module>config-server</module>
    <module>gateway-server</module>
  </modules>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spotify.version>1.2.2</spotify.version>
    <docker.image.tag>alpine</docker.image.tag>
    <actuator.version>3.1.10</actuator.version>
    <spring-boot.version>3.1.10</spring-boot.version>
    <starter-bootstrap.version>4.1.2</starter-bootstrap.version>
    <config.version>4.1.1</config.version>
    <spring-cloud.version>2022.0.4</spring-cloud.version>
    <spring-boot-autoconfigure.version>3.1.10</spring-boot-autoconfigure.version>
    <spring-boot-starter-web.vertion>3.1.10</spring-boot-starter-web.vertion>
    <spring-cloud-starter-netflix-eureka.vertion>4.1.1</spring-cloud-starter-netflix-eureka.vertion>
    <spring-cloud-starter-netflix-eureka-client.vertion>4.1.1</spring-cloud-starter-netflix-eureka-client.vertion>
    <spring-cloud-starter-netflix-eureka-server.vertion>4.1.1</spring-cloud-starter-netflix-eureka-server.vertion>
    <spring-cloud-starter-gateway.vertion>4.1.1</spring-cloud-starter-gateway.vertion>
    <spring-webflux.vertion>6.0.15</spring-webflux.vertion>
    <gson.vertion>2.10.1</gson.vertion>
    <jackson-core.vertion>2.17.0</jackson-core.vertion>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bootstrap</artifactId>
      <version>${starter-bootstrap.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-config -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
      <version>${config.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <version>${actuator.version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.9</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <!-- Import dependency management from Spring Boot -->
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.1.10</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>