<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.bookstore</groupId>
  <artifactId>microservices</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>bookstore-service</module>
    <module>eureka-server</module>
    <module>config-server</module>
    <module>gateway-server</module>
  </modules>

  <profiles>
    <profile>
      <id>Dev</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <env>dev</env>
        <spring.profiles.active>dev</spring.profiles.active>
      </properties>
    </profile>

    <profile>
      <id>QA</id>
      <properties>
        <env>qa</env>
        <spring.profiles.active>qa</spring.profiles.active>
      </properties>
    </profile>
  </profiles>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spotify.version>1.2.2</spotify.version>
    <docker.image.tag>alpine</docker.image.tag>
    <actuator.version>3.1.10</actuator.version>
    <spring-boot.version>3.1.10</spring-boot.version>
    <spring-data-commons.version>3.1.10</spring-data-commons.version>
    <spring-data-relational.version>3.1.10</spring-data-relational.version>
    <starter-bootstrap.version>4.1.2</starter-bootstrap.version>
    <config.version>4.1.1</config.version>
    <spring-cloud.version>2022.0.4</spring-cloud.version>
    <spring-boot-autoconfigure.version>3.1.10</spring-boot-autoconfigure.version>
    <spring-boot-starter-web.version>3.1.10</spring-boot-starter-web.version>
    <spring-cloud-starter-netflix-eureka.version>4.1.1</spring-cloud-starter-netflix-eureka.version>
    <spring-cloud-starter-netflix-eureka-client.version>4.1.1</spring-cloud-starter-netflix-eureka-client.version>
    <spring-cloud-starter-netflix-eureka-server.version>4.1.1</spring-cloud-starter-netflix-eureka-server.version>
    <spring-cloud-starter-gateway.version>4.1.1</spring-cloud-starter-gateway.version>
    <spring-webflux.version>6.0.15</spring-webflux.version>
    <gson.version>2.10.1</gson.version>
    <jackson-core.version>2.15.4</jackson-core.version>
    <jackson-databind.version>2.15.4</jackson-databind.version>
    <liquibase.version>4.27.0</liquibase.version>
    <commons-dbcp2.version>2.12.0</commons-dbcp2.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bootstrap</artifactId>
      <version>${starter-bootstrap.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-config -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
      <version>${config.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <version>${actuator.version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.9</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <!-- Import dependency management from Spring Boot -->
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.1.10</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>