gatewayserver:
  property: Development property
server:
  port: 8090
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: author-service
          uri: lb://AUTHOR-SERVICE
          predicates:
            - Path=/author/**
        - id: publisher-service
          uri: lb://PUBLISHER-SERVICE
          predicates:
            - Path=/publisher/**
        - id: genre-service
          uri: lb://GENRE-SERVICE
          predicates:
            - Path=/genre/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/book/**
        - id: bookstore-service
          uri: lb://BOOKSTORE-SERVICE
          predicates:
            - Path=/bookstore/**
  application:
    name: gateway-service
logging:
  level:
    com.netfliex: DEBUG
    org.springframework: DEBUG
    com:
      mkyong: OFF
      zaxxer: OFF
    root: OFF
eureka:
  instance:
    hostname: gateway-service
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
management:
  endpoints:
    health:
      show-details: always
      diskspace:
        enabled: true
    beans:
      enabled: true
    shutdown:
      enabled: true
    info:
      enabled: true
#    web:
#      exposure:
#        include: 'gateway'
    enabled-by-default: true