spring:
  main:
    lazy-initialization: true
  application:
    name: publisher-service
  config:
    import: optional:configserver:http://localhost:8071
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  level:
    level:
      root: "warn"
    org:
      springframework:
        web: "debug"
      publisher:
        profiler:
          CustomPerformanceMonitorInterceptor: TRACE