version: '3.3'
services:
  gatewayserver:
    image: gatewayserver:alpine
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gatewayserver"
networks:
  backend:
    external: true
    driver: bridge
