version: '3.8'
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5832:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "learning"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    #      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: configserver:alpine
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: eurekaserver:alpine
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    image: gatewayserver:alpine
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gatewayserver"
  bookstoreservice:
    image: book-store:alpine
    environment:
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
      environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
#      gatewayserver:
#        condition: service_started
    ports:
      - "8080:8080"
    links:
      - eurekaserver
      - configserver
    networks:
      - backend
networks:
  backend:
    external: true
    driver: bridge