version: '3.3'
services:
  configserver:
    image: configserver:alpine
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: eurekaserver:alpine
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    image: gatewayserver:alpine
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gatewayserver"
  bookstoreservice:
    image: book-store:alpine
    environment:
        CONFIGSERVER_URI: "http://configserver:8071"
        CONFIGSERVER_PORT: "8071"
    depends_on:
        configserver:
          condition: service_started
        eurekaserver:
          condition: service_started
        gatewayserver:
          condition: service_started
    ports:
        - "8080:8080"
    links:
        - eurekaserver
        - configserver
    networks:
        - backend
networks:
  backend:
    external: true
    driver: bridge