--changeset ibodnar:base-table-structure splitStatements:FALSE
CREATE TABLE authors
(
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL,
  email TEXT NOT NULL
);

CREATE TABLE genres
(
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE books
(
  isbn             TEXT          NOT NULL PRIMARY KEY,
  title            TEXT          NOT NULL,
  publisher        TEXT          NOT NULL,
  publication_date DATE          NOT NULL,
  genre_id         BIGINT        NOT NULL references genres (id),
  description      TEXT          NOT NULL,
  language         TEXT          NOT NULL,
  pages            INT           NOT NULL,
  price            NUMERIC(7, 2) NOT NULL
);

CREATE table books_to_authors
(
  book_isbn TEXT   NOT NULL REFERENCES books (isbn),
  author_id BIGINT NOT NULL REFERENCES authors (id)
);

--changeset ibodnar:adding-images-table-and-relation splitStatements:false
CREATE TABLE images
(
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL
);

ALTER TABLE books
  ADD COLUMN image_id BIGINT REFERENCES images (id);

--changeset ibodnar:adding-publishers-table splitStatements:false
CREATE TABLE publishers
(
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

ALTER TABLE books DROP COLUMN publisher;
ALTER TABLE books
  ADD COLUMN publisher_id BIGINT NOT NULL references publishers (id);