version: '3.8'
services:
  configserver:
    image: configserver:alpine
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
networks:
  backend:
    external: true
