spring:
  application:
    name: bookstoreservice
  datasource:
    url: 'jdbc:postgresql://localhost:5432/learning'
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      netfliex: DEBUG
      springframework: DEBUG

eureka:
  instance:
    hostname: bookstore-service
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka