version: '3.3'
services:
  bookstoreservice:
    image: book-store:alpine
    environment:
      CONFIGSERVER_URI: "http://192.168.70.73:8071"
      CONFIGSERVER_PORT: '8071'
#    depends_on:
#      configserver:
#        condition: service_started
#      eurekaserver:
#        condition: service_started
    ports:
      - "8080:8080"
    links:
      - eurekaserver
      - configserver
    networks:
      - backend
