bookstoreservice:
  property: Default property

spring:
  application:
    name: bookstoreservice
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog.sql

management:
  endpoint:
    health:
      diskspace:
        enabled: true
    beans:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: DEBUG
    org.springframework: DEBUG
    com:
      mkyong: OFF
      zaxxer: OFF
    root: DEBUG

eureka:
  instance:
    hostname: bookstoreservice
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spmia-realm