bookstoreservice:
  property: Default property

spring:
  application:
    name: bookstoreservice
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false

hibernate:
  show_sql: true
  dialect: org.hibernate.dialect.PostgreSQLDialect
  batch.size: 200
  hbm2ddl.auto: update

management:
  endpoint:
    health:
      diskspace:
        enabled: true
    beans:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: INFO
    org.springframework: INFO
    com:
      mkyong: OFF
      zaxxer: OFF
    root: DEBUG

eureka:
  instance:
    hostname: bookstoreservice
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka