eurekaserver:
  property: Development property

spring:
  application:
    name: eurekaserver

server:
  port: 8761
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    hostname: localhost
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/actuator/info/
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/actuator/health/
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix: DEBUG
    org.springframework: DEBUG
    com:
      mkyong: OFF
      zaxxer: OFF
    root: OFF

management:
  endpoints:
    web:
      exposure:
        include: "*"


