gatewayserver:
  property: Default property

spring:
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      enabled: true
      discovery.locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - TokenRelay=
      routes:
        - id: bookstoreservice
          uri: lb://bookstoreservice
          predicates:
            - Path=/bookstore/**
          filters:
            - RewritePath=/bookstore/(?<path>.*), /$\{path}
  application:
    name: gatewayserver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.70.73:8180/realms/spmia-realm
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ostock
            client-secret: 5eG9Qxp2TGkOVEpjTVhnMPnGE5NACFq9
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          keycloak:
            issuer-uri: http://192.168.70.73:8180/realms/spmia-realm

server:
  port: 8081

eureka:
  instance:
    hostname: 192.168.70.73
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.70.73:8761/eureka/

management:
  endpoints:
    health:
      show-details: always
      diskspace:
        enabled: true
    beans:
      enabled: true
    shutdown:
      enabled: true
    info:
      enabled: true
    web:
      exposure:
        include: 'gateway'
    enabled-by-default: true

logging:
  level:
    com.netflix: DEBUG


