gatewayserver:
  property: Development property

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: bookstoreservice
          uri: http://localhost:8080/
          predicates:
            - Path=/bookstore/**
          filters:
            - RewritePath=/bookstore/(?<path>.*), /$\{path}

server:
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/