version: '3.3'
services:
  bookstoreservice:
    image: bookstore-web-application:alpine
#    environment:
#      CONFIGSERVER_URI: "http://192.168.70.73:8071"
#      CONFIGSERVER_PORT: '8071'
    ports:
      - "4200:4200"
networks:
  backend:
    driver: bridge
