version: '3.3'
services:
  bookstore-web-application:
    image: bookstore-web-application:alpine
    ports:
      - "4200:4200"
    networks:
      backend:
        aliases:
          - "bookstore-web-application"
networks:
  backend:
    driver: bridge
